import type { IntroLanguage } from './introLanguage'

const COPY: Record<string, Record<IntroLanguage, string>> = {
  'Coach workspace': { en: 'Coach workspace', ro: 'Spațiu pentru antrenor', th: 'พื้นที่โค้ช' },
  'Your clients, plans and reviews in one private place.': { en: 'Your clients, plans and reviews in one private place.', ro: 'Clienții, planurile și revizuirile tale într-un singur loc privat.', th: 'ลูกค้า แผน และการทบทวนของคุณอยู่ในพื้นที่ส่วนตัวเดียวกัน' },
  'Development access': { en: 'Development access', ro: 'Acces de dezvoltare', th: 'สิทธิ์สำหรับการพัฒนา' },
  'Sponsored seats': { en: 'Sponsored seats', ro: 'Locuri sponsorizate', th: 'สิทธิ์ลูกค้าที่สนับสนุน' },
  'Invite a client': { en: 'Invite a client', ro: 'Invită un client', th: 'เชิญลูกค้า' },
  'Client email': { en: 'Client email', ro: 'E-mailul clientului', th: 'อีเมลลูกค้า' },
  'What they may share': { en: 'What they may share', ro: 'Ce poate partaja', th: 'ข้อมูลที่ลูกค้าอนุญาตให้แชร์' },
  'Visual progress is always a separate opt-in.': { en: 'Visual progress is always a separate opt-in.', ro: 'Progresul vizual necesită mereu acord separat.', th: 'ภาพความคืบหน้าต้องยินยอมแยกต่างหากเสมอ' },
  'Request visual progress': { en: 'Request visual progress', ro: 'Solicită progresul vizual', th: 'ขอสิทธิ์ดูภาพความคืบหน้า' },
  'Create private invite': { en: 'Create private invite', ro: 'Creează invitație privată', th: 'สร้างคำเชิญส่วนตัว' },
  'Copy invite link': { en: 'Copy invite link', ro: 'Copiază linkul', th: 'คัดลอกลิงก์คำเชิญ' },
  'Invite copied': { en: 'Invite copied', ro: 'Invitație copiată', th: 'คัดลอกคำเชิญแล้ว' },
  'Search clients': { en: 'Search clients', ro: 'Caută clienți', th: 'ค้นหาลูกค้า' },
  'No clients yet': { en: 'No clients yet', ro: 'Încă nu ai clienți', th: 'ยังไม่มีลูกค้า' },
  'Needs attention': { en: 'Needs attention', ro: 'Necesită atenție', th: 'ต้องตรวจสอบ' },
  'Up to date': { en: 'Up to date', ro: 'La zi', th: 'เป็นปัจจุบัน' },
  'Shared overview': { en: 'Shared overview', ro: 'Privire de ansamblu partajată', th: 'ภาพรวมที่แชร์' },
  'Only categories this client consented to are visible.': { en: 'Only categories this client consented to are visible.', ro: 'Sunt vizibile doar categoriile acceptate de client.', th: 'จะแสดงเฉพาะหมวดที่ลูกค้ายินยอมเท่านั้น' },
  'Workouts in 30 days': { en: 'Workouts in 30 days', ro: 'Antrenamente în 30 de zile', th: 'การออกกำลังกายใน 30 วัน' },
  'Average daily energy': { en: 'Average daily energy', ro: 'Energie zilnică medie', th: 'พลังงานเฉลี่ยต่อวัน' },
  'Average daily water': { en: 'Average daily water', ro: 'Apă zilnică medie', th: 'น้ำเฉลี่ยต่อวัน' },
  'Current weight': { en: 'Current weight', ro: 'Greutate actuală', th: 'น้ำหนักปัจจุบัน' },
  'Plan studio': { en: 'Plan studio', ro: 'Studio de planuri', th: 'สตูดิโอแผน' },
  'Plan title': { en: 'Plan title', ro: 'Titlul planului', th: 'ชื่อแผน' },
  'Objective': { en: 'Objective', ro: 'Obiectiv', th: 'เป้าหมาย' },
  'Coach note': { en: 'Coach note', ro: 'Nota antrenorului', th: 'บันทึกจากโค้ช' },
  'Review date': { en: 'Review date', ro: 'Data revizuirii', th: 'วันที่ทบทวน' },
  'Add session': { en: 'Add session', ro: 'Adaugă sesiune', th: 'เพิ่มเซสชัน' },
  'Session name': { en: 'Session name', ro: 'Numele sesiunii', th: 'ชื่อเซสชัน' },
  'Guided': { en: 'Guided', ro: 'Ghidată', th: 'แบบมีคำแนะนำ' },
  'Tracked': { en: 'Tracked', ro: 'Monitorizată', th: 'แบบบันทึกเอง' },
  'minutes': { en: 'minutes', ro: 'minute', th: 'นาที' },
  'Warm-up note': { en: 'Warm-up note', ro: 'Notă pentru încălzire', th: 'บันทึกวอร์มอัพ' },
  'Find a reviewed movement': { en: 'Find a reviewed movement', ro: 'Caută o mișcare verificată', th: 'ค้นหาท่าที่ผ่านการตรวจสอบ' },
  'Add movement': { en: 'Add movement', ro: 'Adaugă mișcare', th: 'เพิ่มท่า' },
  'sets': { en: 'sets', ro: 'serii', th: 'เซ็ต' },
  'reps': { en: 'reps', ro: 'repetări', th: 'ครั้ง' },
  'rest': { en: 'rest', ro: 'pauză', th: 'พัก' },
  'per side': { en: 'per side', ro: 'pe fiecare parte', th: 'ต่อข้าง' },
  'Optional': { en: 'Optional', ro: 'Opțional', th: 'ทำหรือไม่ก็ได้' },
  'Remove': { en: 'Remove', ro: 'Elimină', th: 'นำออก' },
  'Publishing check': { en: 'Publishing check', ro: 'Verificare înainte de publicare', th: 'ตรวจสอบก่อนเผยแพร่' },
  'Save draft': { en: 'Save draft', ro: 'Salvează schița', th: 'บันทึกร่าง' },
  'Publish to client': { en: 'Publish to client', ro: 'Publică pentru client', th: 'เผยแพร่ให้ลูกค้า' },
  'Plan published': { en: 'Plan published', ro: 'Plan publicat', th: 'เผยแพร่แผนแล้ว' },
  'Draft saved': { en: 'Draft saved', ro: 'Schiță salvată', th: 'บันทึกร่างแล้ว' },
  'Choose a client first.': { en: 'Choose a client first.', ro: 'Alege mai întâi un client.', th: 'เลือกลูกค้าก่อน' },
  'Your coach plan': { en: 'Your coach plan', ro: 'Planul antrenorului tău', th: 'แผนจากโค้ชของคุณ' },
  'Provided by': { en: 'Provided by', ro: 'Oferit de', th: 'จัดทำโดย' },
  'Read-only grace period': { en: 'Read-only grace period', ro: 'Perioadă de grație doar pentru citire', th: 'ช่วงผ่อนผันแบบอ่านอย่างเดียว' },
  'Your last valid plan stays visible, but it cannot be changed or activated.': { en: 'Your last valid plan stays visible, but it cannot be changed or activated.', ro: 'Ultimul plan valid rămâne vizibil, dar nu poate fi schimbat sau activat.', th: 'แผนล่าสุดยังดูได้ แต่แก้ไขหรือเปิดใช้ไม่ได้' },
  'Nothing has been published yet.': { en: 'Nothing has been published yet.', ro: 'Încă nu a fost publicat niciun plan.', th: 'ยังไม่มีแผนที่เผยแพร่' },
  'Acknowledge plan': { en: 'Acknowledge plan', ro: 'Confirmă planul', th: 'รับทราบแผน' },
  'Activate plan': { en: 'Activate plan', ro: 'Activează planul', th: 'เปิดใช้แผน' },
  'Plan active': { en: 'Plan active', ro: 'Plan activ', th: 'แผนกำลังใช้งาน' },
  'Privacy controls': { en: 'Privacy controls', ro: 'Controlul confidențialității', th: 'การควบคุมความเป็นส่วนตัว' },
  'You decide what your coach can see.': { en: 'You decide what your coach can see.', ro: 'Tu decizi ce poate vedea antrenorul.', th: 'คุณเป็นผู้เลือกข้อมูลที่โค้ชดูได้' },
  'Save sharing choices': { en: 'Save sharing choices', ro: 'Salvează opțiunile', th: 'บันทึกการแชร์' },
  'End coach access': { en: 'End coach access', ro: 'Încheie accesul antrenorului', th: 'ยุติสิทธิ์โค้ช' },
  'Coach access ended': { en: 'Coach access ended', ro: 'Accesul antrenorului s-a încheiat', th: 'ยุติสิทธิ์โค้ชแล้ว' },
  'Accept coach invitation': { en: 'Accept coach invitation', ro: 'Acceptă invitația antrenorului', th: 'ยอมรับคำเชิญจากโค้ช' },
  'Review every category before sharing. You can change these choices later.': { en: 'Review every category before sharing. You can change these choices later.', ro: 'Verifică fiecare categorie înainte de partajare. Poți modifica alegerile ulterior.', th: 'ตรวจสอบทุกหมวดก่อนแชร์ และเปลี่ยนได้ภายหลัง' },
  'Accept and continue': { en: 'Accept and continue', ro: 'Acceptă și continuă', th: 'ยอมรับและดำเนินการต่อ' },
  'Invitation accepted': { en: 'Invitation accepted', ro: 'Invitație acceptată', th: 'ยอมรับคำเชิญแล้ว' },
  'Private by default': { en: 'Private by default', ro: 'Privat în mod implicit', th: 'เป็นส่วนตัวโดยค่าเริ่มต้น' },
  'Coach tools are not enabled for this account.': { en: 'Coach tools are not enabled for this account.', ro: 'Instrumentele pentru antrenor nu sunt activate pentru acest cont.', th: 'บัญชีนี้ยังไม่ได้เปิดใช้เครื่องมือโค้ช' },
  'Return home': { en: 'Return home', ro: 'Înapoi acasă', th: 'กลับหน้าหลัก' },
}

export function coachText(value: string, language: IntroLanguage): string {
  return COPY[value]?.[language] ?? value
}

export const COACH_SCOPE_LABELS: Record<string, Record<IntroLanguage, string>> = {
  nutrition: { en: 'Nutrition', ro: 'Nutriție', th: 'โภชนาการ' },
  workouts: { en: 'Workouts', ro: 'Antrenamente', th: 'การออกกำลังกาย' },
  activity: { en: 'Daily activity', ro: 'Activitate zilnică', th: 'กิจกรรมประจำวัน' },
  hydration: { en: 'Hydration', ro: 'Hidratare', th: 'น้ำดื่ม' },
  supplements: { en: 'Supplements', ro: 'Suplimente', th: 'อาหารเสริม' },
  avatar: { en: 'Avatar scores', ro: 'Scoruri avatar', th: 'คะแนนอวตาร' },
  measurements: { en: 'Body measurements', ro: 'Măsurători corporale', th: 'สัดส่วนร่างกาย' },
  notes: { en: 'Check-in notes', ro: 'Note de monitorizare', th: 'บันทึกเช็กอิน' },
  recovery: { en: 'Recovery', ro: 'Recuperare', th: 'การฟื้นตัว' },
  visual_progress: { en: 'Visual progress photos', ro: 'Fotografii de progres', th: 'ภาพความคืบหน้า' },
}
