/* Staged import probe: find exactly which module stalls or throws. */
const log = (m: string): void => console.log(`[probe ${new Date().toISOString()}] ${m}`)
log('node alive')
try {
  log('importing date-fns')
  await import('date-fns')
  log('date-fns ok')
  log('importing mealTiming')
  await import('../../../src/lib/mealTiming.ts')
  log('mealTiming ok')
  log('importing mealRhythm')
  await import('../../../src/lib/mealRhythm.ts')
  log('mealRhythm ok')
  log('importing nutrition')
  await import('../../../src/lib/nutrition.ts')
  log('nutrition ok')
  log('importing rpg')
  const rpg = await import('../../../src/lib/rpg.ts')
  log(`rpg ok computeEngine=${typeof rpg.computeEngine}`)
  log('importing seed')
  const seed = await import('../../../src/data/seed.ts')
  log(`seed ok buildSeedData=${typeof seed.buildSeedData}`)
  const data = seed.buildSeedData('99999999-0000-4000-8000-000000000001', 'constantine')
  log(`seed built: ${data.program_days.length} days, ${data.exercises.length} exercises`)
  const result = rpg.computeEngine({ ...data, profile: { ...data.profile!, baseline_date: '2026-06-01' } }, '2026-08-10')
  log(`engine ran: ${result.snapshots.length} snapshots, last overall ${result.snapshots.at(-1)?.overall}`)
} catch (err) {
  log(`FAILED: ${err instanceof Error ? `${err.name}: ${err.message}\n${err.stack?.split('\n').slice(0, 6).join('\n')}` : String(err)}`)
  process.exit(1)
}
process.exit(0)
