/*
 * Golden parity: the Swift FitnessBrainEngine must reproduce the web
 * engine's outputs exactly. Fixtures are generated by running the REAL
 * TypeScript engine (Tools/generate-parity-fixtures.mts); if the web brain
 * changes, regenerate and this suite tells you precisely where the Swift
 * port drifted.
 */
import XCTest
@testable import APEX

private struct Fixture: Decodable, Sendable {
    let generated_on: String
    let scenarios: [Scenario]
}

private struct Scenario: Decodable, Sendable {
    let name: String
    let through_date: String
    let input: Input
    let expected: Expected
}

private struct Input: Decodable, Sendable {
    let profile: FBProfile
    let settings_addons: Addons?
    let program_days: [FBProgramDayRef]
    let exercises: [FBExerciseRef]
    let workout_sessions: [FBWorkoutSession]
    let workout_logs: [FBWorkoutLog]
    let daily_logs: [FBDailyLog]
    let health_metrics: [FBHealthMetric]
    let imported_activities: [FBImportedActivity]
}

private struct Addons: Decodable, Sendable {
    let recovery_history: [FBRecoveryCheckin]?
    let meal_rhythm_history: [String: FBMealRhythmDayRaw]?
}

private struct Expected: Decodable, Sendable {
    let targets: FBTargets
    let snapshot_count: Int
    let first_snapshot: FBSnapshot?
    let last_snapshot: FBSnapshot?
    let sampled_snapshots: [FBSnapshot]
    let synergies: [FBSynergyEvent]
}

final class FitnessBrainParityTests: XCTestCase {
    private static let fixture: Fixture = {
        guard let url = Bundle(for: FitnessBrainParityTests.self)
            .url(forResource: "engine-parity", withExtension: "json"),
            let data = try? Data(contentsOf: url) else {
            fatalError("engine-parity.json missing from test bundle")
        }
        return try! JSONDecoder().decode(Fixture.self, from: data)
    }()

    private func engineInput(_ input: Input) -> FBEngineInput {
        FBEngineInput(
            profile: input.profile,
            programDays: input.program_days,
            exercises: input.exercises,
            workoutSessions: input.workout_sessions,
            workoutLogs: input.workout_logs,
            dailyLogs: input.daily_logs,
            healthMetrics: input.health_metrics,
            importedActivities: input.imported_activities,
            recoveryHistory: input.settings_addons?.recovery_history ?? [],
            mealRhythmHistory: input.settings_addons?.meal_rhythm_history ?? [:]
        )
    }

    private func assertSnapshot(
        _ got: FBSnapshot?, _ want: FBSnapshot?, scenario: String, which: String
    ) {
        guard let want else { return }
        guard let got else {
            XCTFail("\(scenario)/\(which): missing snapshot")
            return
        }
        XCTAssertEqual(got.date, want.date, "\(scenario)/\(which) date")
        for (label, g, w) in [
            ("overall", got.overall, want.overall),
            ("health", got.health, want.health),
            ("joint", got.joint, want.joint),
            ("flexibility", got.flexibility, want.flexibility),
            ("endurance", got.endurance, want.endurance),
            ("strength", got.strength, want.strength),
            ("strength_upper", got.strengthUpper, want.strengthUpper),
            ("strength_lower", got.strengthLower, want.strengthLower),
        ] {
            XCTAssertEqual(g, w, accuracy: 1e-9, "\(scenario)/\(which)/\(label) on \(want.date)")
        }
    }

    func testAllScenariosMatchWebEngine() {
        for scenario in Self.fixture.scenarios {
            let result = FitnessBrainEngine.compute(
                engineInput(scenario.input), throughDate: scenario.through_date)

            XCTAssertEqual(
                result.snapshots.count, scenario.expected.snapshot_count,
                "\(scenario.name): snapshot count")
            assertSnapshot(result.snapshots.first, scenario.expected.first_snapshot,
                scenario: scenario.name, which: "first")
            assertSnapshot(result.snapshots.last, scenario.expected.last_snapshot,
                scenario: scenario.name, which: "last")

            let sampled = result.snapshots.enumerated()
                .filter { $0.offset % 7 == 0 }
                .map(\.element)
            XCTAssertEqual(sampled.count, scenario.expected.sampled_snapshots.count,
                "\(scenario.name): sampled count")
            for (got, want) in zip(sampled, scenario.expected.sampled_snapshots) {
                assertSnapshot(got, want, scenario: scenario.name, which: "sampled")
            }

            XCTAssertEqual(result.synergies.count, scenario.expected.synergies.count,
                "\(scenario.name): synergy count. got \(result.synergies.map(\.label))")
            for (got, want) in zip(result.synergies, scenario.expected.synergies) {
                XCTAssertEqual(got.date, want.date, scenario.name)
                XCTAssertEqual(got.kind, want.kind, scenario.name)
                XCTAssertEqual(got.label, want.label, scenario.name)
            }
        }
    }

    func testTargetsMatchWebEngine() {
        for scenario in Self.fixture.scenarios {
            let got = FitnessBrainTargets.computeTargets(
                scenario.input.profile, asOf: Self.fixture.generated_on)
            let want = scenario.expected.targets
            XCTAssertEqual(got.bmrMifflin, want.bmrMifflin, accuracy: 1e-9, "\(scenario.name) mifflin")
            XCTAssertEqual(got.bmrKatch, want.bmrKatch, accuracy: 1e-9, "\(scenario.name) katch")
            XCTAssertEqual(got.tdee, want.tdee, accuracy: 1e-9, "\(scenario.name) tdee")
            XCTAssertEqual(got.kcal, want.kcal, accuracy: 1e-9, "\(scenario.name) kcal")
            XCTAssertEqual(got.proteinG, want.proteinG, accuracy: 1e-9, "\(scenario.name) protein")
            XCTAssertEqual(got.fatG, want.fatG, accuracy: 1e-9, "\(scenario.name) fat")
            XCTAssertEqual(got.carbsG, want.carbsG, accuracy: 1e-9, "\(scenario.name) carbs")
            XCTAssertEqual(got.waterL, want.waterL, accuracy: 1e-9, "\(scenario.name) water")
        }
    }

    /* Date math must agree with date-fns for the ranges the engine replays */
    func testDateArithmetic() {
        XCTAssertEqual(FBDate.daysBetween("2026-06-01", "2026-08-10"), 70)
        XCTAssertEqual(FBDate.addDays("2026-06-01", 0), "2026-06-01")
        XCTAssertEqual(FBDate.addDays("2026-06-01", 30), "2026-07-01")
        XCTAssertEqual(FBDate.addDays("2026-06-01", -60), "2026-04-02")
        XCTAssertEqual(FBDate.addDays("2024-02-28", 1), "2024-02-29")
        XCTAssertEqual(FBDate.addDays("2026-12-31", 1), "2027-01-01")
        XCTAssertEqual(FitnessBrainTargets.ageFrom(birthdate: "1992-07-25", asOf: "2026-07-24"), 33)
        XCTAssertEqual(FitnessBrainTargets.ageFrom(birthdate: "1992-07-25", asOf: "2026-07-25"), 34)
    }
}
